### ISSUE TITLE
not working with nestjs 8

### ISSUE THREAD

**Issue by wodka** [dmitriy-nz/nestjs-form-data#10]
it seems like nestjs 8 will require peerDependencies to be set so that no second version of nestJs core get installed.

else it will fail with:

```
ERROR [ExceptionHandler] Nest can't resolve dependencies of the FormDataInterceptor (Symbol(Inject token for NestJsFormData global configuration object), ?). Please make sure that the argument Reflector at index [1] is available in the NestjsFormDataModule context.

Potential solutions:
- If Reflector is a provider, is it part of the current NestjsFormDataModule?
- If Reflector is exported from a separate @Module, is that module imported within NestjsFormDataModule?
  @Module({
    imports: [ /* the Module containing Reflector */ ]
  })

```

**Comment by dmitriy-nz** [comment]
Hi, thanks for the feedback.
The problem is fixed in version 1.4.5 which is already available on npm

**Comment by wodka** [comment]
just tried it out. 

# **it works!**  - thank you!


but it still installs the additional node_modules:
![image](https://user-images.githubusercontent.com/385731/127971408-cbbfa905-ab40-4f8e-85c3-3b2542caa0e6.png)

I have tried it and it also works with the 8.0.5 version of nestjs - I forced this by adding the resolutions to package.json:

```
  "resolutions": {
    "@nestjs/common": "8.0.5",
    "@nestjs/core": "8.0.5",
    "@nestjs/platform-express": "8.0.5",
    "@nestjs/testing": "8.0.5"
  },
```

so perhaps it might also fix the problem to add the dependencies for nestjs 7 + 8 and allow it in the peer dependencies with the same version

**Comment by dmitriy-nz** [comment]
Are you using yarn? 
I didn't find any documentation at [docs.npmjs.com](https://docs.npmjs.com/cli/v7/configuring-npm/package-json) for the resolutions object in package.json
I'll set up peerDependencies to avoid duplication

**Comment by wodka** [comment]
yes I'm using yarn - thought there is a similar thing with npm as well^^

**Comment by dmitriy-nz** [comment]
I have configured peerDependencies, try version 1.4.7 with npm

**Comment by wodka** [comment]
just tried it - it now also with yarn no longer installs the sub packages! thank you for changing this.

**Comment by dmitriy-nz** [comment]
Thank you for noticing this 🙂

**Comment by yepMad** [comment]
I'm still facing this on 8.0.0
