### ISSUE TITLE
@HasMimeType and @MaxFileSize only work for @IsFile

### ISSUE THREAD

**Issue by Thiti-Dev** [dmitriy-nz/nestjs-form-data#11]
The decorators such as HasMimeType, MaxFileSize . . . only works for Single image file -> @IsFile

But when I tried with the @isFiles -> {Array of FileSystemStoreFile} with {each:true} -> no matter what the mime or size is it will be always valid without getting the validation error

![image](https://user-images.githubusercontent.com/36455825/128688566-50ecad28-8647-42b6-9750-cd005032fd5f.png)

**Comment by dmitriy-nz** [comment]
Hi, try not to use the @Type (() => Array) decorator on an array of files.

**Comment by Thiti-Dev** [comment]
@dmitriy-nz 

Ahh It was my fault, I tested this with postman and I forget to set the form-data field to be an array
And yeah type casting isn't needed

Now everything works fine

Thank you

**Comment by dmitriy-nz** [comment]
Glad I helped you! In any case, an error should have been thrown when checking @IsFiles(). I will check it 😉
