### ISSUE TITLE
Race condition - using originalFilename in full path

### ISSUE THREAD

**Issue by Tomas2D** [dmitriy-nz/nestjs-form-data#16]
Hey, firstly thanks for this library, it is very useful.

I find out a situation where you can get a race condition. When you receive simultaneously multiple requests where each request has same `originalName` the target file will be overridden and thus the application can crash later on.

These lines are responsible for that:

https://github.com/dmitriy-nz/nestjs-form-data/blob/ecf063c4c5d58673f7a135ecd975dab592e1f69c/src/classes/storage/FileSystemStoredFile.ts#L18-L21

I propose the way of generating UUID for it instead of using original name of the file. It can be also a security issue probably, but I am not sure.

If you want I can make a PR.

Thanks!

**Comment by dmitriy-nz** [comment]
Hey! Thanks for your feedback!
I will look into this issue shortly

**Comment by dmitriy-nz** [comment]
I have released a new version 1.5.0 with a fix for this problem, please check

**Comment by Tomas2D** [comment]
It works as expected. Thank you!
