### ISSUE TITLE
Replace unsupported busboy version with fastify fork

### ISSUE THREAD

**Issue by Uzlopak** [dmitriy-nz/nestjs-form-data#17]
Hi,

we forked busboy and fixed two critical bugs in the package, which could cause the node-process to crash or to hang. We also improved the performance and added some new features. It does not have breaking changes so it is a drop-in-replacement for busboy. It has a code coverage of about 95%.

https://github.com/fastify/busboy/blob/master/CHANGELOG.md
https://github.com/fastify/busboy
https://www.npmjs.com/package/@fastify/busboy

for tracking reasons:
fastify/busboy#68

**Comment by dmitriy-nz** [comment]
Hi! I see a big acceleration compared to the version busboy@0.3.1
But there is a new version of busboy which is much better. (nestjs-form-data now using 1.6.0)
Maybe you have performance comparison tests of the new versions of the libraries?

**Comment by dmitriy-nz** [comment]
Closed due to inactivity
