### ISSUE TITLE
Support Fastify ❓

### ISSUE THREAD

**Issue by roman-supy-io** [dmitriy-nz/nestjs-form-data#18]
Hey, amazing plugin, but ...
do you plan to add support for `fastify`?

**Comment by dmitriy-nz** [comment]
Hi, so far I have not planned for fastify support. 
Having looked a little at the amount of work, I can say that it will not take much time, so it can be implemented

**Comment by roman-supy-io** [comment]
@dmitriy-nz thank you and if you need any help in implementing this, tell me

**Comment by kevindehoux** [comment]
Fastify will be a great enhancement for this lib, hope to see soon ! I really need it personnaly

**Comment by dmitriy-nz** [comment]
Added fastify support in nestjs-form-data@1.9.2.
Thanks to [0x67](https://github.com/dmitriy-nz/nestjs-form-data/pull/53)
