### ISSUE TITLE
support NestJS v8

### ISSUE THREAD

**Issue by micalevisk** [dmitriy-nz/nestjs-form-data#19]
Hi! can you please try to support the latest major version of NestJS?

https://github.com/dmitriy-nz/nestjs-form-data/blob/b53fca4c0d92665e542672da1512f711b4ee10df/package.json?#L44-L45

**Comment by dmitriy-nz** [comment]
Hi! I will check it soon

**Comment by dmitriy-nz** [comment]
Nestjs v8 support has been updated

**Comment by micalevisk** [comment]
if it still work for nestjs v7, then you'll need to change the peer deps semver range. Also, as nestjs v8 requires rxjs v7, you'll need to change that peer deps as well:

```json
"@nestjs/common": "^7.3.0 || ^8.0.0",
"@nestjs/core": "^7.3.0 || ^8.0.0",
"rxjs": "^6.6.3 || ^7.1.0"
```

**Comment by micalevisk** [comment]
I guess it would be even better you bump all `@nestjs/*` of your deps and dev deps, just to make sure the tests are still passing for nestjs v8 :)
