### ISSUE TITLE
Add support for async register

### ISSUE THREAD

**Issue by Tomas2D** [dmitriy-nz/nestjs-form-data#2]
Hey, firstly I want to thank you for this library. It is exactly what I was missing.

I propose to add support for async config to be able to create options asynchronously.

```typescript
NestjsFormDataModule.registerAsync({
  useFactory: async () => {
    const config = await getConfig();

    ...

    return config;
  },
}),
```

Thanks.

**Comment by dmitriy-nz** [comment]
@Tomas2D Hey! Thanks for the good feedback.
I added support for asynchronous configuration in version 1.4, new version is already available.
https://github.com/dmitriy-nz/nestjs-form-data#async-configuration
