### ISSUE TITLE
Update nestjs version to 8

### ISSUE THREAD

**Issue by unkindypie** [dmitriy-nz/nestjs-form-data#20]
Most of the nestjs community packages already on 8 version so that it's impossible to install their latest version without --legacy-peer-deps/--force flags. Could you please update your wonderful library to support newest version of the nest?

**Comment by dmitriy-nz** [comment]
Hi! I will check it soon, thanks for the feedback!

**Comment by dmitriy-nz** [comment]
@unkindypie I'm generating a new nestjs 8 app and the dependency installs without any issues. Please show your package.json or console output during installation
``` 
"dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "nestjs-form-data": "^1.6.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
"devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@nestjs/schematics": "^8.0.0",
    "@nestjs/testing": "^8.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "27.0.2",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^27.2.5",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "^27.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.10.1",
    "typescript": "^4.3.5"
  },

```
nest-cli version `8.2.0`

**Comment by danrdzprz** [comment]
I have the same problem. I'm going to show my console output. 

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: api-rrhh@0.0.1
npm ERR! Found: rxjs@7.5.2
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"^7.2.0" from the root project
npm ERR!   peer rxjs@"^7.1.0" from @nestjs/common@8.2.6
npm ERR!   node_modules/@nestjs/common
npm ERR!     @nestjs/common@"^8.0.0" from the root project
npm ERR!     peer @nestjs/common@"^8.0.0" from nestjs-form-data@1.6.0
npm ERR!     node_modules/nestjs-form-data
npm ERR!       nestjs-form-data@"*" from the root project
npm ERR!     5 more (@nestjs/core, @nestjs/microservices, ...)
npm ERR!   4 more (@nestjs/core, @nestjs/microservices, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^6.6.3" from nestjs-form-data@1.6.0
npm ERR! node_modules/nestjs-form-data
npm ERR!   nestjs-form-data@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by dmitriy-nz** [comment]
@danrdzprz @unkindypie Hi! try to use version 1.6.1
