### ISSUE TITLE
Array of files request example

### ISSUE THREAD

**Issue by matgott** [dmitriy-nz/nestjs-form-data#3]
Hi, I'am triying to validate an array of files but I don't know how the request must be made.

This is my DTO:
```
import { ApiProperty } from '@nestjs/swagger';
import { IsBooleanString, IsNotEmpty, IsNumberString, IsString } from 'class-validator';
import { HasMimeType, IsFiles, MemoryStoredFile } from 'nestjs-form-data';
import { BaseDto } from 'src/modules/base/dto/base-dto';

export class createDto extends BaseDto {
  @ApiProperty({ type: 'number' })
  @IsNumberString()
  @IsNotEmpty()
  readonly companyBranch;

  @ApiProperty({ type: 'number' })
  @IsNumberString()
  @IsNotEmpty()
  readonly entryUser;

  @ApiProperty({ type: 'number' })
  @IsNumberString()
  @IsNotEmpty()
  readonly sinisterType;

  @ApiProperty({ type: 'number' })
  @IsNumberString()
  @IsNotEmpty()
  readonly sinisterNumber;

  @ApiProperty({ type: 'string' })
  @IsNotEmpty()
  @IsString()
  readonly formType;

  @ApiProperty({ type: 'boolean' })
  @IsBooleanString()
  readonly isCanceled;

  @ApiProperty({ type: 'files' })
  @IsFiles({ each: true })
  @HasMimeType(['image/jpeg', 'image/png'], { each: true })
  readonly photos: MemoryStoredFile[];
}
```

And this is my request with postman:
![imagen](https://user-images.githubusercontent.com/16677716/118678841-c077ef00-b7d3-11eb-91c4-bd0b5194fcc7.png)
But still asking me for an array of photos.

Thanks in advance!

**Comment by dmitriy-nz** [comment]
Hey! To validate an array of files, you can use the decorator `@IsFile({ each: true })` or `@IsFiles()` 
IsFiles decorator does not need to pass each option

**Comment by matgott** [comment]
> 
> 
> Hey! To validate an array of files, you can use the decorator `@IsFile({ each: true })` or `@IsFiles()`
> IsFiles decorator does not need to pass each option

Hi dmitriy! Without "each: true" in isFiles() I receive an error:
![imagen](https://user-images.githubusercontent.com/16677716/118685950-ed2f0500-b7d9-11eb-9a91-57681ebe221b.png)

**Comment by matgott** [comment]
With isFile({each: true}) works, maybe is a bug with isFiles().

Other thing, the data is parsed like this:
![imagen](https://user-images.githubusercontent.com/16677716/118686690-9c6bdc00-b7da-11eb-9beb-ab566c0578b6.png)

Is strange, the property "photos" isn't an array, but has nested object with the other file.

**Comment by dmitriy-nz** [comment]
Yes you are right, I just released version 1.4.1 which fixed the problem
Thank you :)

**Comment by matgott** [comment]
> 
> 
> Yes you are right, I just released version 1.4.1 which fixed the problem
> Thank you :)

Thanks you for the quickly response. Now I don't receive that eror with isFiles but, with postman still asking me for an array of photos:

![imagen](https://user-images.githubusercontent.com/16677716/118687464-69761800-b7db-11eb-80e5-492bbc747a80.png)

**Comment by dmitriy-nz** [comment]
Try like this
![image](https://user-images.githubusercontent.com/51157176/118688068-5f214180-b80e-11eb-83e8-0fa1b66fe17e.png)
When sending an array as data, you must specify the index

**Comment by matgott** [comment]
But with isFile({each: true}) works great! But, then probably there is a bug with isFiles()

> 
> 
> Try like this
> ![image](https://user-images.githubusercontent.com/51157176/118689019-436a6b00-b80f-11eb-8a13-10d9345d47d6.png)
> When sending an array as data, you must specify the index
> or like this
> ![image](https://user-images.githubusercontent.com/51157176/118689331-8af0f700-b80f-11eb-8897-24c695ad69b6.png)

Amazing, thanks!

**Comment by dmitriy-nz** [comment]
Use `@IsFile({each: true})` must be paired with`@IsArray()` decorator
If you look closely, then when transferring an array of files without [] or [index] leads to the fact that there is only one file object in the field

For example
DTO
```
export class FormDataTestDto {

  @IsFile({ each: true })
  @HasMimeType(['image/jpeg', 'image/png'], { each: true })
  photos: FileSystemStoredFile[];

}
```
Request
![image](https://user-images.githubusercontent.com/51157176/118691310-9cd39980-b811-11eb-872f-11588394a80a.png)
Debugger
![image](https://user-images.githubusercontent.com/51157176/118691564-e15f3500-b811-11eb-961a-a8e19ed42f96.png)
photos is not an array
These are the features of the work of the mapper from form data to object

**Comment by dmitriy-nz** [comment]
Maybe it needs to be documented
