### ISSUE TITLE
Check file type based on buffer instead of extension

### ISSUE THREAD

**Issue by 0x67** [dmitriy-nz/nestjs-form-data#31]
So right now the I guess it only check for file type based on its extension, do you plan to add support for it?
This is quite an edge cases but simple to implement using [file-type](https://www.npmjs.com/package/file-type) library.

**Comment by dmitriy-nz** [comment]
Hi, right now the file check is done via mime type which is given by busboy
![image](https://user-images.githubusercontent.com/51157176/187031977-5e507859-c5fa-43e3-9939-06882a43d692.png)
good idea to check the file type via a magic number, we should add some validation decorators. thanks for idea

**Comment by 0x67** [comment]
Ah my own decorator use file-type to check the buffer, I can rewrite it to use busboy then I'll submit a PR

**Comment by dmitriy-nz** [comment]
I have already started the implementation, there will be a new version soon with built-in decorators to check file extensions via file-type. It will check the type via incoming stream from busboy, this will improve version backward compatibility. I also added some tests for this

**Comment by 0x67** [comment]
I'm looking forward to it 🙂

And thank you for the awesome library!

**Comment by dmitriy-nz** [comment]
Hi, version 1.8.0 has been released!
Please check new version and [change log](https://github.com/dmitriy-nz/nestjs-form-data/blob/master/CHANGELOG.md)

**Comment by 0x67** [comment]
Hi @dmitriy-nz, I ran tests in my projects with the new version and it looks good
Thank you!
