### ISSUE TITLE
mimetype problem

### ISSUE THREAD

**Issue by eroo36** [dmitriy-nz/nestjs-form-data#32]
I was not able to import "FileSystemStoredFile" for some reason (might be something about my machine only)
After the last update, I cannot get the mime type using "mimetype" parameter from a "StoredFile".
This is what I get when I console log : 

```js
{
  originalName: 'tst.png',
  encoding: '7bit',
  busBoyMimeType: 'image/png',
  path: '/path-to-file/tst-8a5935.png',
  size: 77290,
  fileType: { ext: 'png', mime: 'image/png' }
}
```

These are the options I have, but mimeType and mimetype are undefined: 

![Screenshot 2022-09-07 at 12 07 04](https://user-images.githubusercontent.com/13486466/188838790-cbbd6942-6002-4348-bdc8-187f4015d721.png)

am i doing something wrong here?

![Screenshot 2022-09-07 at 12 10 32](https://user-images.githubusercontent.com/13486466/188839684-f5e8801e-e9f2-489e-ae9b-f17a9fccd5bd.png)

For now i am gonna stick with older version

**Comment by dmitriy-nz** [comment]
Hi! I will check it soon, thanks for the feedback

**Comment by dmitriy-nz** [comment]
Please provide your controller, dto and package.json or nestjs version
Or check your environment.

I released v1.8.1 with small fixes, you can try new version

**Comment by eroo36** [comment]
> Please provide your controller, dto and package.json or nestjs version Or check your environment.
> 
> I released v1.8.1 with small fixes, you can try new version

Thanks, I will try the new version, can close this if it was already working for you.

**Comment by justiniruuza** [comment]
I have the same issue with the latest version `1.8.3`

![image](https://user-images.githubusercontent.com/96718437/200236143-7d6f700d-af73-444b-b2ef-5229bd4cd4fd.png)

**Comment by justiniruuza** [comment]
The weird thing, I have another project with the same version but it works well. I'm not sure how can I debug this to find where the issue
