### ISSUE TITLE
Cannot find module 'node:stream' or its corresponding type declarations.

### ISSUE THREAD

**Issue by sousawalker** [dmitriy-nz/nestjs-form-data#34]
I get this error, when include the module in my app.

My version of nestjs is: 7.1.1

![image](https://user-images.githubusercontent.com/1927838/189115090-7d5eec3a-f602-45e2-9256-67f31185404e.png)

**Comment by dmitriy-nz** [comment]
hi, your issue fixed in new version 1.8.1 please check it out
