### ISSUE TITLE
[SUGGESTION] Allow an `isGlobal` option in the config

### ISSUE THREAD

**Issue by BayBreezy** [dmitriy-nz/nestjs-form-data#41]
Hey, thanks for the library.

Is it possible to add an `isGlobal` option to the config object? That way we don't have to import the `NestjsFormDataModule` into every module that needs it.
Currently, the doc says to just add it to the `app.module` file, but doing this does not make it globally available.

**Comment by dmitriy-nz** [comment]
Good idea, it will be implemented in new versions

**Comment by justinphan1992** [comment]
Hi, are you working on this one? If not, I can work on it?

**Comment by BayBreezy** [comment]
@justinphan1992 I would suggest you implement it and do a PR.
When @dmitriy-nz gets the time he can look it over and merge.
Please. Thanks ❤️

**Comment by dmitriy-nz** [comment]
Hi again! I release new version [1.8.6](https://www.npmjs.com/package/nestjs-form-data/v/1.8.6) where the parameter for global configuration is added, please check the new version
