### ISSUE TITLE
Error on install with class validator

### ISSUE THREAD

**Issue by ronnahmias** [dmitriy-nz/nestjs-form-data#45]
npm ERR! Found: class-validator@0.13.2
npm ERR! node_modules/class-validator
npm ERR!   class-validator@"^0.13.2" from the root project
npm ERR!   peerOptional class-validator@"*" from @nestjs/common@9.2.1

my package.json:
"dependencies": {
    "@nestjs-modules/mailer": "^1.8.1",
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/jwt": "^9.0.0",
    "@nestjs/passport": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/swagger": "^6.1.3",
    "@nestjs/typeorm": "^9.0.1",
    "aws-sdk": "^2.1258.0",
    "bcrypt": "^5.1.0",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.13.2",
    "fs": "^0.0.1-security",
    "handlebars": "^4.7.7",
    "json2csv": "^5.0.7",
    "passport-jwt": "^4.0.0",
    "pg": "^8.8.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0",
    "typeorm": "^0.3.10",
    "uuid": "^9.0.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.2.0",
    "@types/express": "^4.17.13",
    "@types/jest": "28.1.8",
    "@types/multer": "^1.4.7",
    "@types/node": "^16.0.0",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "28.1.3",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "28.0.8",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.1.0",
    "typescript": "^4.7.4"
  },

**Comment by aramgyulnazaryan** [comment]
I have the same issue.

**Comment by aramgyulnazaryan** [comment]
![Untitled](https://user-images.githubusercontent.com/19376722/208432942-f37b1ecc-6cca-4784-83a6-a30fc99ae238.png)

**Comment by dmitriy-nz** [comment]
Hi! Must be fixed in version nestjs-form-data@1.8.7  
Please check

**Comment by dzzk** [comment]
Hi Dmitriy, is there a plan for the version with no class-validator 0.13.2? Tnx.
