### ISSUE TITLE
returning invalid array format when uploading multiple files

### ISSUE THREAD

**Issue by Pangeran29** [dmitriy-nz/nestjs-form-data#47]
hello.. 
i try to upload many image using nestjs-form-data but the array response is not valid array of objects, and i can't iterate it
this is my dto configuration:
`@ApiProperty({
    type: 'array',
    items: {
      type: 'string',
      format: 'binary',
    },
    required: true,
  })
  @IsNotEmpty()
  @IsFile({ each: true })
  @MaxFileSize(2000000, { each: true })
  @HasMimeType(['image/jpeg', 'image/png', 'image/jpg'], { each: true })
  banner: FileSystemStoredFile[];`
  
  and when i try console.log it returning invalid array format
  `[
  originalName: 'picture_991_posterproduk-masarasara-pants-1-sz.png',
  encoding: '7bit',
  busBoyMimeType: 'image/png',
  path: 'D:\\nguli\\maxsol\\goon\\public\\banner\\picture_991_posterproduk-masarasara-pants-1-sz-87b8a7.png',
  size: 114098,
  fileType: { ext: 'png', mime: 'image/png' },
  '': FileSystemStoredFile {
    originalName: 'Screenshot 2022-09-07 160046.png',
    encoding: '7bit',
    busBoyMimeType: 'image/png',
    path: 'D:\\nguli\\maxsol\\goon\\public\\banner\\Screenshot 2022-09-07 160046-7b8a72.png',
    size: 284564,
    fileType: { ext: 'png', mime: 'image/png' },
    '': FileSystemStoredFile {
      originalName: 'Screenshot 2022-09-07 160046.png',
      encoding: '7bit',
      busBoyMimeType: 'image/png',
      path: 'D:\\nguli\\maxsol\\goon\\public\\banner\\Screenshot 2022-09-07 160046-b8a721.png',
      size: 284564,
      fileType: [Object]
    }
  }
]`

is this the right response when uploading array of image in nestjs-form-data??

**Comment by dmitriy-nz** [comment]
Hi, show how you send a request, e.g. through a rest client such as postman or insomnia

**Comment by Pangeran29** [comment]
@dmitriy-nz yes, i use swagger to send the request. this is how it looks in swagger 
![image](https://github.com/dmitriy-nz/nestjs-form-data/assets/88958502/c3a9a7c0-0514-4f80-9e35-ed24987b7756)
and this is the curl (banner is the array of image that i send)
![image](https://github.com/dmitriy-nz/nestjs-form-data/assets/88958502/e23df359-12aa-445f-a849-c04d30ddd7ca)

**Comment by dmitriy-nz** [comment]
@Pangeran29 Please note the readme, the section "Validation of file arrays"
https://github.com/dmitriy-nz/nestjs-form-data#validate-the-array-of-file
The key must be in the format "key[]".
I don't quite understand what's wrong with your array output in the log, please make it readable

**Comment by reislucaz** [comment]
![image](https://github.com/dmitriy-nz/nestjs-form-data/assets/101826551/e45c8d7d-c937-44f3-b054-5f206d57c1e6)

**Comment by nikola418** [comment]
Any progress on this issue?

**Comment by dmitriy-nz** [comment]
@nikola418 
Please read doc: 

1. You must use the `IsFiles `decorator to validate an array of files. 
https://github.com/dmitriy-nz/nestjs-form-data#isfiles
2. You must explicitly show arrays in your Multipart Form keys. 
https://github.com/dmitriy-nz/nestjs-form-data#validate-the-array-of-file.  
Actually, it should work and yes, I did some investigation and the `append-field` library used to parse field keys and build the multi level object is not working as it should.
I don't have a lot of time right now, I'll get to it soon.

**Comment by nikola418** [comment]
1. did
2. did

**Comment by dmitriy-nz** [comment]
I use this library in many projects, including for loading arrays of files, if you follow the readme.
Anyway, I fixed a bug in the `node-append-field` library in version 1.9.1 and now everything should work fine without explicitly specifying the array sign in the file key.
Open the issue again if the problem occurred after updating to version 1.9.1.

**Comment by Altair200333** [comment]
> Here is a very dirty workaround: `@Transform((obj) => { const arr = []; let field = obj.value; while (field) { const temp = field['']; delete field['']; arr.push(Object.assign(new FileSystemStoredFile(), field)); field = temp; } return arr; })`

i think this can be shortened to this, which also worked for me:

```ts
@Transform(({ obj }) => obj.files)
```

**Comment by dmitriy-nz** [comment]
This issue was completely fixed in the v1.9.9, please reopen issue if you still have that problem.
