### ISSUE TITLE
Support for Nestjs 10

### ISSUE THREAD

**Issue by BayBreezy** [dmitriy-nz/nestjs-form-data#48]
Nest update to v10 recently, but the peer dependencies are capped at v9. Can this be bumped soon please ? Thanks

**Comment by xino1010** [comment]
waiting...

**Comment by dmitriy-nz** [comment]
Hi, NestJs 10 support was added in 1.9.0 version.

**Comment by BayBreezy** [comment]
Thank you

**Comment by xino1010** [comment]
thank you
