### ISSUE TITLE
@IsFiles() decorator with custom message causes 400 bad request

### ISSUE THREAD

**Issue by karolmodzelewski** [dmitriy-nz/nestjs-form-data#49]
Hi,

When I'm trying to send a request (POST) with multiple files and I set a custom error message to `@IsFiles()` decorator, it will cause a 400 bad request error. Request are send here using Postman

My code (DTO):
```
    @IsFiles({ message: 'IsFiles custom error message' })
    @MaxFileSize(1024 * 1024 * 5, { each: true, message: 'MaxFileSize custom error message' })
    @HasMimeType(['image/jpeg', 'image/png', 'image/webp'], { each: true, message: 'HasMimeType custom error message' })
    @IsNotEmpty({ message: 'IsNotEmpty custom error message' })
    public photos: FileSystemStoredFile[];
```

![1](https://github.com/dmitriy-nz/nestjs-form-data/assets/45852121/cda663e3-f574-4d32-b12f-af23de96c7bb)

And when I delete an object with message parameter:

```
    @IsFiles() // <-- here
    @MaxFileSize(1024 * 1024 * 5, { each: true, message: 'MaxFileSize custom error message' })
    @HasMimeType(['image/jpeg', 'image/png', 'image/webp'], { each: true, message: 'HasMimeType custom error message' })
    @IsNotEmpty({ message: 'IsNotEmpty custom error message' })
    public photos: FileSystemStoredFile[];
```

It works perfectly

![2](https://github.com/dmitriy-nz/nestjs-form-data/assets/45852121/213c8eca-4d95-4209-9512-d57112295e58)

It also works when I use `@IsFile()` decorator with `each` property like this:

`@IsFile({ each: true, message: 'IsFile custom error message' }) `

========

`NestJS: 9`
`nestjs-form-data: 1.8.7`

**Comment by dmitriy-nz** [comment]
@karolmodzelewski Hi, in version 1.9.1 I have added tests to check your ticket. And they pass successfully, could you please test the new version in your environment and report the results?
