### ISSUE TITLE
Is it possible to remove debugger label in source code?

### ISSUE THREAD

**Issue by bogdanovna** [dmitriy-nz/nestjs-form-data#65]
_First of all - thank you for such cool lib and my issue has more propose or even ask character. So..._

I often run my code with debugger and because `nestjs-form-data` is worked perfectly for me (thanks a lot!) I simply don't want to go into this breakpoint. But it happen every time even if I omit all breakpoints. And I think this is because of this `breakpoint` statement.

![image](https://github.com/user-attachments/assets/48c07d8f-caa7-40f6-b3d3-758e6ff28afb)

**Comment by pantharius** [comment]
Is this removed from code? If yes, can someone tell the version that fix this ? Thanks a lot

**Comment by dmitriy-nz** [comment]
I've just deployed a `1.9.92` version, debugger was removed here. Thanks for the issue
