### ISSUE TITLE
Is it battle-tested?

### ISSUE THREAD

**Issue by unkindypie** [dmitriy-nz/nestjs-form-data#7]
Is this lib ready for production? Can it handle the same load as multer does? I'm currently picking lib for my project and not sure which more suitable for production at the moment.

**Comment by dmitriy-nz** [comment]
This library, like [multer](https://www.npmjs.com/package/multer), is a wrapper over [busboy](https://github.com/mscdex/busboy), it has the maximum performance.
But you need to understand that validation through DTO decorators works after the file is loaded, while validation through the `limits` object when decorating `@FormDataRequest` will work during file loading, which is a more performant solution.

Also, for uploading large files, you should use the `FileSystemStoredFile` storage.

**Comment by unkindypie** [comment]
Thanks for the answers. Seems that your lib is the best currently available solution for using formdata with nestjs.
