### ISSUE TITLE
Transform and IsInt for arrays are not working

### ISSUE THREAD

**Issue by unkindypie** [dmitriy-nz/nestjs-form-data#9]
DTO:
```
export class RegisterAccountDto {
   ...

  @ApiProperty({ type: [Number] })
  @Transform(({ value }) => {
    return Number(value);
  })
  @IsInt({ each: true })
  expertiseKeywordIds: number[];

}
```
Payload:

![image](https://user-images.githubusercontent.com/34601252/123975576-1e4c4900-d9c6-11eb-8daf-43450319ee8b.png)

Route handler gets this value:

`expertiseKeywordIds: 1
`

Without any decorators everything works although I need to parse and validate array manually.  IsInt without Transform have the same bug.

**Comment by dmitriy-nz** [comment]
Hi, the problem is that you transform the array of strings into a number. @Transform decorator is not called for every value of the array, but only for the entire array. 
![image](https://user-images.githubusercontent.com/51157176/124002505-7e4ee980-d9de-11eb-8f8e-e49597f9cb10.png)

**Comment by dmitriy-nz** [comment]
Please read the documentation for [class-transformer](https://www.npmjs.com/package/class-transformer)
You can use this decorator to convert an array of strings to an array of numbers

```
//ToNumber.ts
export function toNumber(value: any) {
  const res: number = +value;
  return (isNaN(res)) ? null : res;
}


export function ToNumber(): (target: any, key: string) => void {
  return Transform((params: TransformFnParams) => toNumber(params.value));
}

//ToArrayNumber.ts
export function toArrayNumber(v: any[]): number[] {
  return (Array.isArray(v))
    ? v.map(v => toNumber(v))
    : null;
}

export function ToArrayNumber(): (target: any, key: string) => void {
  return Transform((params: TransformFnParams) => toArrayNumber(params.value));
}
```

**Comment by unkindypie** [comment]
My bad, thank you for the explanation.
